python ./demo/run_interaction_nlp.py --save_root="../results/20250313_try_baseline_squad_large" \
  --gpu_id=1 \
  --model="qwen2.5-14b#pretrain" \
  --dataset="custom-cn-us-manual-100" \
  --data_path="../datasets/custom-cn-us-manual-100" \
  --selected_dim="gt-log-odds" \
  --gt_type="predict" \
  --player_path="../players/custom-cn-us-manual-100/players-qwen-manual-phrase" \
  --loss="l1" \
  --baseline_type="learned" \
  --learned_baseline_identifier="squad-large-from-cqa-epoch85" \
  --background_type="ori" \
  --cal_batch_size=256 \
  --verbose=1 \
  --sparse_mode="pq" \
  --optimizer="sgd" \
  --lr=1e-6 \
  --auto_lr="v1" \
  --momentum=0.999 \
  --niters=50000 \
  --qcoef=0.01 \
  --qstd="mean-vN-v0" \
  --reorg=1 &

python ./demo/run_interaction_nlp.py --save_root="../results/20250313_try_baseline_squad_large" \
  --gpu_id=4 \
  --model="qwen2.5-14b#pretrain" \
  --dataset="custom-cn-us-manual-100" \
  --data_path="../datasets/custom-cn-us-manual-100" \
  --selected_dim="gt-log-odds" \
  --gt_type="predict" \
  --player_path="../players/custom-cn-us-manual-100/players-qwen-manual-phrase" \
  --loss="l1" \
  --baseline_type="learned" \
  --learned_baseline_identifier="squad-large-from-cqa-epoch85" \
  --background_type="ori" \
  --cal_batch_size=256 \
  --verbose=1 \
  --sparse_mode="pq" \
  --optimizer="sgd" \
  --lr=1e-6 \
  --auto_lr="v1" \
  --momentum=0.999 \
  --niters=50000 \
  --qcoef=0.05 \
  --qstd="mean-vN-v0" \
  --reorg=1 &

#python ./demo/run_interaction_nlp.py --save_root="../results/20250305_try_cn_us_manual_100_deepseek" \
#  --gpu_id=0 \
#  --model="deepseek-r1-distill-1.5b#pretrain" \
#  --dataset="custom-cn-us-manual-100" \
#  --data_path="../datasets/custom-cn-us-manual-100" \
#  --selected_dim="gt-log-odds" \
#  --gt_type="predict" \
#  --player_path="../players/custom-cn-us-manual-100/players-deepseek-r1-distill-qwen-manual-phrase" \
#  --loss="l1" \
#  --baseline_type="learned" \
#  --learned_baseline_identifier="superbowl-from-cqa-lr1e-4-epoch100-fix-bos" \
#  --background_type="ori" \
#  --cal_batch_size=256 \
#  --verbose=1 \
#  --sparse_mode="pq" \
#  --optimizer="sgd" \
#  --lr=1e-6 \
#  --auto_lr="v1" \
#  --momentum=0.999 \
#  --niters=50000 \
#  --qcoef=0.05 \
#  --qstd="mean-vN-v0" \
#  --reorg=1 &

#python ./demo/run_interaction_nlp.py --save_root="../results/20250305_try_cn_us_manual_100_deepseek" \
#  --gpu_id=1 \
#  --model="deepseek-r1-distill-1.5b#pretrain" \
#  --dataset="custom-cn-us-manual-100" \
#  --data_path="../datasets/custom-cn-us-manual-100" \
#  --selected_dim="gt-log-odds" \
#  --gt_type="predict" \
#  --player_path="../players/custom-cn-us-manual-100/players-deepseek-r1-distill-qwen-manual-phrase" \
#  --loss="l1" \
#  --baseline_type="learned" \
#  --learned_baseline_identifier="superbowl-from-cqa-lr1e-4-epoch100-fix-bos-anneal" \
#  --background_type="ori" \
#  --cal_batch_size=256 \
#  --verbose=1 \
#  --sparse_mode="pq" \
#  --optimizer="sgd" \
#  --lr=1e-6 \
#  --auto_lr="v1" \
#  --momentum=0.999 \
#  --niters=50000 \
#  --qcoef=0.05 \
#  --qstd="mean-vN-v0" \
#  --reorg=1 &
#
#python ./demo/run_interaction_nlp.py --save_root="../results/20250305_try_cn_us_manual_100_deepseek" \
#  --gpu_id=5 \
#  --model="deepseek-r1-distill-7b#pretrain" \
#  --dataset="custom-cn-us-manual-100" \
#  --data_path="../datasets/custom-cn-us-manual-100" \
#  --selected_dim="gt-log-odds" \
#  --gt_type="predict" \
#  --player_path="../players/custom-cn-us-manual-100/players-deepseek-r1-distill-qwen-manual-phrase" \
#  --loss="l1" \
#  --baseline_type="learned" \
#  --learned_baseline_identifier="superbowl-from-cqa-lr1e-4-epoch100-fix-bos-anneal" \
#  --background_type="ori" \
#  --cal_batch_size=256 \
#  --verbose=1 \
#  --sparse_mode="pq" \
#  --optimizer="sgd" \
#  --lr=1e-6 \
#  --auto_lr="v1" \
#  --momentum=0.999 \
#  --niters=50000 \
#  --qcoef=0.05 \
#  --qstd="mean-vN-v0" \
#  --reorg=1 &