python ./demo/run_interaction_nlp.py --save_root="../results/20250326_try_squad_from_sw" \
  --gpu_id=3 \
  --model="BERTweet#pretrain" \
  --dataset="custom-squad-from-sw" \
  --data_path="../datasets/custom-squad-from-sw" \
  --selected_dim="gt-log-odds" \
  --gt_type="predict" \
  --player_path="../players/custom-squad-from-sw/players-pythia-from-sw" \
  --baseline_type="unk" \
  --background_type="ori" \
  --cal_batch_size=1024 \
  --interaction_type="shapley_taylor" \
  --verbose=1 \
  # --sparse_mode="pq" \
  # --optimizer="sgd" \
  # --lr=1e-7 \
  # --auto_lr="v1" \
  # --momentum=0.999 \
  # --niters=50000 \
  # --qcoef=0.05
  # --loss="l1" \
# 对于generation, 还得看一下 selected_dim 要不要用gt-log-odds-1000

# python ./demo/run_interaction_nlp.py --save_root="../results/20250118_try_squad_from_sw" \
#   --gpu_id=1 \
#   --model="pythia-6.9b#pretrain" \
#   --dataset="custom-squad-from-sw" \
#   --data_path="../datasets/custom-squad-from-sw" \
#   --selected_dim="gt-log-odds" \
#   --gt_type="predict" \
#   --player_path="../players/custom-squad-from-sw/players-pythia-from-sw" \
#   --loss="l1" \
#   --baseline_type="unk" \
#   --background_type="ori" \
#   --cal_batch_size=1024 \
#   --verbose=1 \
#   --sparse_mode="pq" \
#   --optimizer="sgd" \
#   --lr=1e-7 \
#   --auto_lr="v1" \
#   --momentum=0.999 \
#   --niters=50000 \
#   --qcoef=0.05