python ./demo/run_interaction_nlp.py --save_root="../results/20250227_try_cn_us_manual_100" \
  --gpu_id=0 \
  --model="qwen2.5-3b#pretrain" \
  --dataset="custom-cn-us-manual-100" \
  --data_path="../datasets/custom-cn-us-manual-100" \
  --selected_dim="gt-log-odds" \
  --gt_type="predict" \
  --player_path="../players/custom-cn-us-manual-100/players-qwen-manual-phrase" \
  --loss="l1" \
  --baseline_type="learned" \
  --learned_baseline_identifier="superbowl-from-cqa-lr1e-5-epoch100-warmup-annealing" \
  --background_type="ori" \
  --cal_batch_size=256 \
  --verbose=1 \
  --sparse_mode="pq" \
  --optimizer="sgd" \
  --lr=1e-6 \
  --auto_lr="v1" \
  --momentum=0.999 \
  --niters=50000 \
  --qcoef=0.05 \
  --qstd="mean-vN-v0" \
  --reorg=1

#python ./demo/run_interaction_nlp.py --save_root="../results/20250227_try_cn_us_manual_100" \
#  --gpu_id=0 \
#  --model="qwen2.5-0.5b#pretrain" \
#  --dataset="custom-cn-us-manual-100" \
#  --data_path="../datasets/custom-cn-us-manual-100" \
#  --selected_dim="gt-log-odds" \
#  --gt_type="predict" \
#  --player_path="../players/custom-cn-us-manual-100/players-qwen-manual-phrase" \
#  --loss="l1" \
#  --baseline_type="learned" \
#  --learned_baseline_identifier="superbowl-from-cqa-lr1e-5-epoch100" \
#  --background_type="ori" \
#  --cal_batch_size=256 \
#  --verbose=1 \
#  --sparse_mode="pq" \
#  --optimizer="sgd" \
#  --lr=1e-6 \
#  --auto_lr="v1" \
#  --momentum=0.999 \
#  --niters=50000 \
#  --qcoef=0.05 \
#  --qstd="mean-vN-v0" \
#  --reorg=1