#python ./demo/run_interaction_nlp.py --save_root="../results/20250318_try_init_model" \
#  --gpu_id=5 \
#  --model="pythia-1.4b#init" \
#  --dataset="custom-cn-us-manual-100" \
#  --data_path="../datasets/custom-cn-us-manual-100" \
#  --selected_dim="gt-log-odds" \
#  --gt_type="predict" \
#  --player_path="../players/custom-cn-us-manual-100/players-pythia-manual-phrase" \
#  --loss="l1" \
#  --baseline_type="unk" \
#  --background_type="ori" \
#  --cal_batch_size=256 \
#  --verbose=1 \
#  --sparse_mode="pq" \
#  --optimizer="sgd" \
#  --lr=1e-6 \
#  --auto_lr="v1" \
#  --momentum=0.999 \
#  --niters=50000 \
#  --qcoef=0.05 \
#  --qstd="mean-vN-v0" \
#  --reorg=1 \
#  --data_type="fp32"

python ./demo/run_interaction_nlp.py --save_root="../results/20250318_try_init_model" \
  --gpu_id=5 \
  --model="LLM360-amber-7b#pretrain_revision=ckpt000" \
  --dataset="custom-cn-us-manual-100" \
  --data_path="../datasets/custom-cn-us-manual-100" \
  --selected_dim="gt-log-odds" \
  --gt_type="predict" \
  --player_path="../players/custom-cn-us-manual-100/players-amber-manual-phrase" \
  --loss="l1" \
  --baseline_type="unk" \
  --background_type="ori" \
  --cal_batch_size=256 \
  --verbose=1 \
  --sparse_mode="pq" \
  --optimizer="sgd" \
  --lr=1e-6 \
  --auto_lr="v1" \
  --momentum=0.999 \
  --niters=50000 \
  --qcoef=0.05 \
  --qstd="mean-vN-v0" \
  --reorg=1 \
  --data_type="auto"